hostname: cv-pathfinder-edge
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.42.1
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
    route_map_in: RM-BGP-UNDERLAY-PEERS-IN
    route_map_out: RM-BGP-UNDERLAY-PEERS-OUT
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    remote_as: '65000'
    ttl_maximum_hops: 1
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: WAN-OVERLAY-PEERS
      activate: false
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  - source_protocol: static
    route_map: RM-STATIC-2-BGP
  neighbors:
  - ip_address: 172.17.0.0
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65199'
    peer: site-ha-disabled-leaf
    description: site-ha-disabled-leaf_Ethernet1
  - ip_address: 192.168.144.1
    peer_group: WAN-OVERLAY-PEERS
    peer: cv-pathfinder-pathfinder
    description: cv-pathfinder-pathfinder
  vrfs:
  - name: IT
    router_id: 192.168.42.1
    neighbors:
    - ip_address: 172.17.0.0
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65199'
      description: site-ha-disabled-leaf_Ethernet1.1000_vrf_IT
    rd: 192.168.42.1:1000
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 1000:1000
      export:
      - address_family: evpn
        route_targets:
        - 1000:1000
    redistribute_routes:
    - source_protocol: connected
  - name: PROD
    router_id: 192.168.42.1
    neighbors:
    - ip_address: 172.17.0.0
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65199'
      description: site-ha-disabled-leaf_Ethernet1.142_vrf_PROD
    rd: 192.168.42.1:142
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 142:142
      export:
      - address_family: evpn
        route_targets:
        - 142:142
    redistribute_routes:
    - source_protocol: connected
  - name: ATTRACTED-VRF-FROM-UPLINK
    router_id: 192.168.42.1
    neighbors:
    - ip_address: 172.17.0.0
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65199'
      description: site-ha-disabled-leaf_Ethernet1.666_vrf_ATTRACTED-VRF-FROM-UPLINK
    rd: 192.168.42.1:666
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 666:666
      export:
      - address_family: evpn
        route_targets:
        - 666:666
    redistribute_routes:
    - source_protocol: connected
  - name: default
    rd: 192.168.42.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      route_map_in: RM-EVPN-SOO-IN
      route_map_out: RM-EVPN-SOO-OUT
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    path_selection:
      roles:
        producer: true
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    bgp:
      additional_paths:
        receive: true
        send:
          any: true
service_routing_protocols_model: multi-agent
ip_routing: true
transceiver_qsfp_default_mode_4x10: false
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
- name: IT
  tenant: TenantA
  ip_routing: true
- name: PROD
  tenant: TenantA
  ip_routing: true
- name: ATTRACTED-VRF-FROM-UPLINK
  tenant: TenantC
  ip_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet52
  peer: site-ha-disabled-leaf
  peer_interface: Ethernet1
  peer_type: l3leaf
  description: P2P_LINK_TO_SITE-HA-DISABLED-LEAF_Ethernet1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 172.17.0.1/31
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
- name: Ethernet52.1000
  peer: site-ha-disabled-leaf
  peer_interface: Ethernet1.1000
  peer_type: l3leaf
  vrf: IT
  description: P2P_LINK_TO_SITE-HA-DISABLED-LEAF_Ethernet1.1000_vrf_IT
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 1000
  mtu: 9214
  ip_address: 172.17.0.1/31
- name: Ethernet52.142
  peer: site-ha-disabled-leaf
  peer_interface: Ethernet1.142
  peer_type: l3leaf
  vrf: PROD
  description: P2P_LINK_TO_SITE-HA-DISABLED-LEAF_Ethernet1.142_vrf_PROD
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 142
  mtu: 9214
  ip_address: 172.17.0.1/31
- name: Ethernet52.666
  peer: site-ha-disabled-leaf
  peer_interface: Ethernet1.666
  peer_type: l3leaf
  vrf: ATTRACTED-VRF-FROM-UPLINK
  description: P2P_LINK_TO_SITE-HA-DISABLED-LEAF_Ethernet1.666_vrf_ATTRACTED-VRF-FROM-UPLINK
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 666
  mtu: 9214
  ip_address: 172.17.0.1/31
- name: Ethernet1
  peer_type: l3_interface
  peer: peer3
  peer_interface: Ethernet42
  ip_address: dhcp
  shutdown: false
  type: routed
  description: ATT_666_peer3_Ethernet42
  dhcp_client_accept_default_route: true
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
- name: Ethernet2
  peer_type: l3_interface
  ip_address: 172.15.5.5/31
  shutdown: false
  type: routed
  description: Colt_10555
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
- name: Ethernet3
  peer_type: l3_interface
  ip_address: 172.20.20.20/31
  shutdown: false
  type: routed
  description: Comcast-5G_AF830
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.42.1/32
as_path:
  access_lists:
  - name: ASPATH-WAN
    entries:
    - type: permit
      match: '65000'
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.42.0/24 eq 32
- name: PL-STATIC-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    action: permit 66.66.66.0/24
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 192.168.42.1:511 additive
- name: RM-BGP-UNDERLAY-PEERS-IN
  sequence_numbers:
  - sequence: 40
    type: permit
    description: Mark prefixes originated from the LAN
    set:
    - extcommunity soo 192.168.42.1:511 additive
- name: RM-BGP-UNDERLAY-PEERS-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Advertise local routes towards LAN
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
    description: Advertise routes received from WAN iBGP towards LAN
    match:
    - route-type internal
- name: RM-EVPN-SOO-IN
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - extcommunity soo 192.168.42.1:511 additive
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
- name: RM-STATIC-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-STATIC-VRF-DEFAULT
    set:
    - extcommunity soo 192.168.42.1:511 additive
static_routes:
- destination_address_prefix: 172.16.0.0/16
  gateway: 172.16.5.4
- destination_address_prefix: 66.66.66.0/24
  gateway: 172.17.0.0
  vrf: default
flow_tracking:
  hardware:
    trackers:
    - name: WAN-FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 5000
      exporters:
      - name: DPI-EXPORTER
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 5000
    shutdown: false
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.42.1:511
ip_security:
  ike_policies:
  - name: CP-IKE-POLICY
    local_id: 192.168.142.1
  sa_policies:
  - name: DP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  - name: CP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  profiles:
  - name: DP-PROFILE
    sa_policy: DP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890666
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: DP-PROFILE
management_security:
  ssl_profiles:
  - name: profileA
    certificate:
      file: profileA.crt
      key: profileA.key
    trust_certificate:
      certificates:
      - aristaDeviceCertProvisionerDefaultRootCA.crt
    tls_versions: '1.2'
router_adaptive_virtual_topology:
  topology_role: edge
  region:
    name: AVD_Land_East
    id: 43
  zone:
    name: DEFAULT-ZONE
    id: 1
  site:
    name: Site511
    id: 511
  profiles:
  - name: DEFAULT-AVT-POLICY-CONTROL-PLANE
    load_balance_policy: LB-DEFAULT-AVT-POLICY-CONTROL-PLANE
  - name: DEFAULT-AVT-POLICY-VIDEO
    load_balance_policy: LB-DEFAULT-AVT-POLICY-VIDEO
  - name: DEFAULT-AVT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-AVT-POLICY-DEFAULT
  - name: PROD-AVT-POLICY-VOICE
    load_balance_policy: LB-PROD-AVT-POLICY-VOICE
  - name: PROD-AVT-POLICY-VIDEO
    load_balance_policy: LB-PROD-AVT-POLICY-VIDEO
  - name: PROD-AVT-POLICY-DEFAULT
    load_balance_policy: LB-PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-POLICY-DEFAULT
  vrfs:
  - name: default
    policy: DEFAULT-AVT-POLICY-WITH-CP
    profiles:
    - name: DEFAULT-AVT-POLICY-CONTROL-PLANE
      id: 254
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: PROD
    policy: PROD-AVT-POLICY
    profiles:
    - name: PROD-AVT-POLICY-VOICE
      id: 2
    - name: PROD-AVT-POLICY-VIDEO
      id: 4
    - name: PROD-AVT-POLICY-DEFAULT
      id: 1
  - name: IT
    policy: DEFAULT-AVT-POLICY
    profiles:
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: ATTRACTED-VRF-FROM-UPLINK
    policy: DEFAULT-POLICY
    profiles:
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
  policies:
  - name: DEFAULT-AVT-POLICY-WITH-CP
    matches:
    - application_profile: APP-PROFILE-CONTROL-PLANE
      avt_profile: DEFAULT-AVT-POLICY-CONTROL-PLANE
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
  - name: PROD-AVT-POLICY
    matches:
    - application_profile: VOICE
      avt_profile: PROD-AVT-POLICY-VOICE
    - application_profile: VIDEO
      avt_profile: PROD-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY
    matches:
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
  - name: DEFAULT-POLICY
    matches:
    - application_profile: default
      avt_profile: DEFAULT-POLICY-DEFAULT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_path_selection:
  tcp_mss_ceiling:
    ipv4_segment_size: auto
  path_groups:
  - name: INET
    id: 101
    local_interfaces:
    - name: Ethernet1
      stun:
        server_profiles:
        - INET-cv-pathfinder-pathfinder-Ethernet1
        - INET-cv-pathfinder-pathfinder-Ethernet3
    dynamic_peers:
      enabled: true
    static_peers:
    - router_ip: 192.168.144.1
      name: cv-pathfinder-pathfinder
      ipv4_addresses:
      - 10.7.7.7
      - 10.9.9.9
    ipsec_profile: CP-PROFILE
  - name: MPLS
    id: 100
    local_interfaces:
    - name: Ethernet2
      stun:
        server_profiles:
        - MPLS-cv-pathfinder-pathfinder-Ethernet2
    dynamic_peers:
      enabled: true
    static_peers:
    - router_ip: 192.168.144.1
      name: cv-pathfinder-pathfinder
      ipv4_addresses:
      - 172.16.0.1
  - name: LTE
    id: 102
    local_interfaces:
    - name: Ethernet3
    dynamic_peers:
      enabled: true
    ipsec_profile: CP-PROFILE
  load_balance_policies:
  - name: LB-DEFAULT-AVT-POLICY-CONTROL-PLANE
    path_groups:
    - name: INET
    - name: MPLS
  - name: LB-DEFAULT-AVT-POLICY-VIDEO
    path_groups:
    - name: MPLS
    - name: INET
  - name: LB-DEFAULT-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
      priority: 42
  - name: LB-PROD-AVT-POLICY-VOICE
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
    jitter: 42
    lowest_hop_count: true
  - name: LB-PROD-AVT-POLICY-VIDEO
    path_groups:
    - name: MPLS
    - name: LTE
    - name: INET
      priority: 2
    loss_rate: '42.0'
  - name: LB-PROD-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
      priority: 2
  - name: LB-DEFAULT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
    - name: LTE
router_traffic_engineering:
  enabled: true
stun:
  client:
    server_profiles:
    - name: INET-cv-pathfinder-pathfinder-Ethernet1
      ip_address: 10.7.7.7
      ssl_profile: profileA
    - name: INET-cv-pathfinder-pathfinder-Ethernet3
      ip_address: 10.9.9.9
      ssl_profile: profileA
    - name: MPLS-cv-pathfinder-pathfinder-Ethernet2
      ip_address: 172.16.0.1
      ssl_profile: profileA
application_traffic_recognition:
  application_profiles:
  - name: VIDEO
    categories:
    - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-1
    - name: skype
  - name: VOICE
    applications:
    - name: CUSTOM-VOICE-APPLICATION
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
  categories:
  - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-2
    - name: microsoft-teams
  applications:
    ipv4_applications:
    - name: CUSTOM-APPLICATION-1
      protocols:
      - tcp
      src_prefix_set_name: CUSTOM-SRC-PREFIX-1
      dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
    - name: CUSTOM-APPLICATION-2
      protocols:
      - tcp
      tcp_src_port_set_name: TCP-SRC-2
      tcp_dest_port_set_name: TCP-DEST-2
    - name: APP-CONTROL-PLANE
      dest_prefix_set_name: PFX-PATHFINDERS
  field_sets:
    l4_ports:
    - name: TCP-SRC-2
      port_values:
      - '42'
    - name: TCP-DEST-2
      port_values:
      - '666'
      - '777'
    ipv4_prefixes:
    - name: CUSTOM-SRC-PREFIX-1
      prefix_values:
      - 42.42.42.0/24
    - name: CUSTOM-DEST-PREFIX-1
      prefix_values:
      - 6.6.6.0/24
    - name: PFX-PATHFINDERS
      prefix_values:
      - 192.168.144.1/32
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9214
  ip_address: 192.168.142.1/32
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
vxlan_interface:
  Vxlan1:
    description: cv-pathfinder-edge_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Dps1
      vrfs:
      - name: default
        vni: 1
      - name: IT
        vni: 100
      - name: PROD
        vni: 42
      - name: ATTRACTED-VRF-FROM-UPLINK
        vni: 166
metadata:
  cv_tags:
    device_tags:
    - name: Role
      value: edge
    - name: Region
      value: AVD_Land_East
    - name: Zone
      value: DEFAULT-ZONE
    - name: Site
      value: Site511
    interface_tags:
    - interface: Ethernet52
      tags:
      - name: Type
        value: lan
    - interface: Ethernet52.1000
      tags:
      - name: Type
        value: lan
    - interface: Ethernet52.142
      tags:
      - name: Type
        value: lan
    - interface: Ethernet52.666
      tags:
      - name: Type
        value: lan
    - interface: Ethernet1
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: ATT
      - name: Circuit
        value: '666'
    - interface: Ethernet2
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Colt
      - name: Circuit
        value: '10555'
    - interface: Ethernet3
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Comcast-5G
      - name: Circuit
        value: AF830
  cv_pathfinder:
    role: edge
    vtep_ip: 192.168.142.1
    region: AVD_Land_East
    zone: DEFAULT-ZONE
    site: Site511
    interfaces:
    - name: Ethernet1
      carrier: ATT
      circuit_id: '666'
      pathgroup: INET
    - name: Ethernet2
      carrier: Colt
      circuit_id: '10555'
      pathgroup: MPLS
    - name: Ethernet3
      carrier: Comcast-5G
      circuit_id: AF830
      pathgroup: LTE
    pathfinders:
    - vtep_ip: 192.168.144.1
