hostname: uplink_lan_wan_router2
is_deployed: true
router_bgp:
  as: '65100'
  router_id: 192.168.1.2
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '65100'
    ttl_maximum_hops: 1
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      route_map_in: RM-EVPN-SOO-IN
      route_map_out: RM-EVPN-SOO-OUT
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    bgp:
      additional_paths:
        receive: true
        send:
          any: true
  vrfs:
  - name: VRF1
    router_id: 192.168.1.2
    rd: 192.168.1.2:123
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 123:123
      export:
      - address_family: evpn
        route_targets:
        - 123:123
    redistribute_routes:
    - source_protocol: connected
  - name: default
    rd: 192.168.1.2:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
service_routing_protocols_model: multi-agent
ip_routing: true
transceiver_qsfp_default_mode_4x10: false
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
- name: VRF1
  tenant: TEST
  ip_routing: true
  ipv6_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet2
  peer: uplink_lan_l2leaf
  peer_interface: Ethernet2
  peer_type: l2leaf
  description: UPLINK_LAN_L2LEAF_Ethernet2
  shutdown: false
  type: routed
  mtu: 9214
- name: Ethernet2.10
  peer: uplink_lan_l2leaf
  peer_interface: Ethernet2 VLAN 10
  peer_type: l2leaf
  description: VLAN10_NATIVE
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 10
  vrf: VRF1
  ip_address: 10.0.10.1/24
  mtu: 9214
- name: Ethernet2.100
  peer: uplink_lan_l2leaf
  peer_interface: Ethernet2 VLAN 100
  peer_type: l2leaf
  description: My vlan 100
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 100
  vrf: VRF1
  ip_address: 10.0.100.1/24
  ipv6_address: cafe::cafe/64
  ipv6_enable: true
  eos_cli: comment yo
  _custom_key: custom_value
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.1.2/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.1.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 192.168.1.2:0 additive
- name: RM-BGP-UNDERLAY-PEERS-IN
  sequence_numbers:
  - sequence: 40
    type: permit
    description: Mark prefixes originated from the LAN
    set:
    - extcommunity soo 192.168.1.2:0 additive
- name: RM-BGP-UNDERLAY-PEERS-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Advertise local routes towards LAN
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
    description: Advertise routes received from WAN iBGP towards LAN
    match:
    - route-type internal
- name: RM-EVPN-SOO-IN
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - extcommunity soo 192.168.1.2:0 additive
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.1.2:0
ip_security:
  ike_policies:
  - name: CP-IKE-POLICY
    local_id: 192.168.2.2
  sa_policies:
  - name: CP-SA-POLICY
  profiles:
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: test
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: CP-PROFILE
management_security:
  ssl_profiles:
  - name: STUN-DTLS
    certificate:
      file: STUN-DTLS.crt
      key: STUN-DTLS.key
    trust_certificate:
      certificates:
      - aristaDeviceCertProvisionerDefaultRootCA.crt
    tls_versions: '1.2'
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_path_selection:
  tcp_mss_ceiling:
    ipv4_segment_size: auto
  load_balance_policies:
  - name: LB-DEFAULT-POLICY-DEFAULT
  - name: LB-DEFAULT-POLICY-CONTROL-PLANE
  policies:
  - name: DEFAULT-POLICY
    default_match:
      load_balance: LB-DEFAULT-POLICY-DEFAULT
  - name: DEFAULT-POLICY-WITH-CP
    rules:
    - id: 10
      application_profile: APP-PROFILE-CONTROL-PLANE
      load_balance: LB-DEFAULT-POLICY-CONTROL-PLANE
    default_match:
      load_balance: LB-DEFAULT-POLICY-DEFAULT
  vrfs:
  - name: VRF1
    path_selection_policy: DEFAULT-POLICY
  - name: default
    path_selection_policy: DEFAULT-POLICY-WITH-CP
application_traffic_recognition:
  application_profiles:
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
  applications:
    ipv4_applications:
    - name: APP-CONTROL-PLANE
      dest_prefix_set_name: PFX-PATHFINDERS
  field_sets:
    ipv4_prefixes:
    - name: PFX-PATHFINDERS
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9214
  ip_address: 192.168.2.2/32
vxlan_interface:
  Vxlan1:
    description: uplink_lan_wan_router2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Dps1
      vrfs:
      - name: VRF1
        vni: 123
      - name: default
        vni: 1
