---
# Inherit most of the variables from CV_PATHFINDERS_TESTS

wan_stun_dtls_profile_name: profileB

wan_route_servers:
  # Not testing the overloading
  - hostname: cv-pathfinder-pathfinder1
  - hostname: cv-pathfinder-pathfinder2
  # This one is not in the inventory pathfinder1 & 2
  - hostname: cv-pathfinder-pathfinder3
    vtep_ip: 6.6.6.6
    path_groups:
      - name: MPLS
        interfaces:
          - name: Ethernet1
            ip_address: 172.17.17.17/31
      - name: INET
        interfaces:
          - name: Ethernet2
            ip_address: 10.50.50.50/31

# Overwriting TTL
bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.142.0/24
      - 192.168.143.0/24
  wan_rr_overlay_peers:
    ttl_maximum_hops: 42
    bfd_timers:
      interval: 2020
      min_rx: 2000
      multiplier: 3
