---
# Testing cv-pathfinder
wan_mode: cv-pathfinder

cv_pathfinder_regions:
  - name: AVD_Land_West
    id: 42
    description: AVD Region
    sites:
      - name: Site422
        id: 422
        location: Somewhere
      - name: Site423
        id: 423
        location: Somewhere-warm
  - name: AVD_Land_East
    id: 43
    description: AVD Region
    sites:
      - name: Site511
        id: 511

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.142.0/24
      - 192.168.143.0/24

wan_stun_dtls_profile_name: profileA

wan_route_servers:
  # Not testing the overloading
  - hostname: cv-pathfinder-pathfinder

wan_ipsec_profiles:
  control_plane:
    shared_key: ABCDEF1234567890
  data_plane:
    shared_key: ABCDEF1234567890666

default_node_types:
  - node_type: wan_rr
    match_hostnames:
      - "cv-pathfinder-pathfinder.*"
  - node_type: wan_router
    match_hostnames:
      - "cv-pathfinder-edge.*"
      - "cv-pathfinder-transit.*"
  - node_type: l3leaf
    match_hostnames:
      - ".*leaf.*"

wan_router:
  defaults:
    loopback_ipv4_pool: 192.168.42.0/24
    vtep_loopback_ipv4_pool: 192.168.142.0/24
    filter:
      always_include_vrfs_in_tenants: [TenantA]
    uplink_ipv4_pool: 172.17.0.0/16
    bgp_as: 65000
  # Testing HA and disabling HA
  node_groups:
    # SITE_HA_DISABLED
    - group: Site511
      uplink_type: p2p-vrfs
      uplink_switches: [ site-ha-disabled-leaf ]
      uplink_interfaces: [ Ethernet52 ]
      cv_pathfinder_region: AVD_Land_East
      cv_pathfinder_site: Site511
      wan_ha:
        enabled: False
      nodes:
        - name: cv-pathfinder-edge
          id: 1
          uplink_switch_interfaces: [Ethernet1]
          l3_interfaces:
            - name: Ethernet1
              peer: peer3
              peer_interface: Ethernet42
              wan_carrier: ATT
              wan_circuit_id: 666
              dhcp_accept_default_route: true
              ip_address: dhcp
            - name: Ethernet2
              wan_carrier: Colt
              wan_circuit_id: 10555
              ip_address: 172.15.5.5/31
              peer_ip: 172.16.5.4
              static_routes:
                - prefix: 172.16.0.0/16
            - name: Ethernet3
              wan_carrier: Comcast-5G
              wan_circuit_id: AF830
              ip_address: 172.20.20.20/31
              connected_to_pathfinder: False
        - name: cv-pathfinder-edge-no-common-path-group
          id: 2
          uplink_switch_interfaces: [Ethernet2]
          l3_interfaces:
            - name: Ethernet1
              wan_carrier: Inmrasat
              wan_circuit_id: S511
              dhcp_accept_default_route: true
              ip_address: dhcp
    # SITE_HA_ENABLED
    - group: Site423
      cv_pathfinder_region: AVD_Land_West
      cv_pathfinder_site: Site423
      uplink_type: p2p-vrfs
      uplink_switches: [ site-ha-enabled-leaf2A, site-ha-enabled-leaf2B ]
      uplink_interfaces: [ Ethernet52, Ethernet53 ]
      nodes:
        - name: cv-pathfinder-edge2A
          id: 2
          l3_interfaces:
            - name: Ethernet1
              wan_carrier: ATT
              wan_circuit_id: 423-01
              dhcp_accept_default_route: true
              ip_address: dhcp
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: cv-pathfinder-edge2B
          id: 3
          l3_interfaces:
            - name: Ethernet2
              wan_carrier: Colt
              wan_circuit_id: 10423
              ip_address: 172.15.6.6/31
          uplink_switch_interfaces: [Ethernet2, Ethernet2]

    # TRANSIT_SITE_HA_ENABLED
    - group: TRANSIT_SITE_HA_ENABLED
      loopback_ipv4_pool: 192.168.43.0/24
      vtep_loopback_ipv4_pool: 192.168.143.0/24
      filter:
        always_include_vrfs_in_tenants: [TenantA, TenantB]
      uplink_ipv4_pool: 172.17.0.0/16
      uplink_type: p2p-vrfs
      uplink_switches: [ site-ha-enabled-leaf1 ]
      uplink_interfaces: [ Ethernet52 ]
      cv_pathfinder_transit_mode: region
      # Disable HA IPsec
      wan_ha:
        ipsec: false
      nodes:
        - name: cv-pathfinder-transit1A
          cv_pathfinder_region: AVD_Land_West
          cv_pathfinder_site: Site422
          id: 1
          uplink_switch_interfaces: [Ethernet1]
          l3_interfaces:
            - name: Ethernet1.42
              wan_carrier: Comcast
              dhcp_accept_default_route: true
              ip_address: dhcp
            - name: Ethernet2.42
              encapsulation_dot1q_vlan: 666
              wan_carrier: Colt
              wan_circuit_id: 10666
              ip_address: 172.16.6.6/31
        - name: cv-pathfinder-transit1B
          cv_pathfinder_region: AVD_Land_West
          cv_pathfinder_site: Site422
          id: 2
          uplink_switch_interfaces: [Ethernet2]
          l3_interfaces:
            - name: Ethernet1.42
              wan_carrier: Comcast
              dhcp_accept_default_route: true
              ip_address: dhcp
            - name: Ethernet2.42
              encapsulation_dot1q_vlan: 666
              wan_carrier: Colt
              wan_circuit_id: 10666
              ip_address: 172.16.6.6/31

# Fake DC1
l3leaf:
  defaults:
    bgp_as: 65199
    loopback_ipv4_pool: 192.168.45.0/24
    vtep_loopback_ipv4_pool: 192.168.255.0/24
    virtual_router_mac_address: 00:1c:73:00:00:01
    filter:
      always_include_vrfs_in_tenants: [TenantA]
  nodes:
    - name: site-ha-enabled-leaf1
      id: 1
    - name: site-ha-enabled-leaf2A
      id: 2
    - name: site-ha-enabled-leaf2B
      id: 3
    - name: site-ha-disabled-leaf
      id: 4

wan_rr:
  defaults:
    loopback_ipv4_pool: 192.168.44.0/24
    vtep_loopback_ipv4_pool: 192.168.144.0/24
    data_plane_cpu_allocation_max: 1
    bgp_as: 65000
  nodes:
    - name: cv-pathfinder-pathfinder
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Bouygues_Telecom
          wan_circuit_id: 777
          static_routes:
            - prefix: 0.0.0.0/0
          ip_address: 10.7.7.7/31
          peer_ip: 10.7.7.6
        - name: Ethernet2
          wan_carrier: Colt
          wan_circuit_id: 10000
          ip_address: 172.16.0.1/31
        - name: Ethernet3
          wan_carrier: Another-ISP
          wan_circuit_id: 999
          ip_address: 10.9.9.9/31
    - name: cv-pathfinder-pathfinder1
      id: 2
      data_plane_cpu_allocation_max: 3
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Orange
          wan_circuit_id: 888
          ip_address: 10.8.8.8/31
    - name: cv-pathfinder-pathfinder2
      id: 3
      data_plane_cpu_allocation_max: 3
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: SFR
          wan_circuit_id: 999
          ip_address: 10.9.9.9/31
        - name: Ethernet2
          wan_carrier: ATT-MPLS
          wan_circuit_id: 10999
          ip_address: 172.19.9.9/31

wan_path_groups:
  - name: MPLS
    ipsec: false
    # TODO remove one once auto-id is implemented - for now required in schema
    id: 100
  - name: INET
    id: 101
  - name: LTE
    id: 102
  - name: Equinix
    id: 103
  - name: Satellite
    id: 104

wan_carriers:
  - name: Comcast
    path_group: INET
  - name: ATT
    path_group: INET
  - name: Bouygues_Telecom
    path_group: INET
  - name: SFR
    path_group: INET
  - name: Orange
    path_group: INET
  - name: Another-ISP
    path_group: INET
  - name: Colt
    path_group: MPLS
  - name: ATT-MPLS
    path_group: MPLS
  - name: Comcast-5G
    path_group: LTE
  - name: Inmrasat
    path_group: Satellite

tenants:
  - name: TenantA
    mac_vrf_vni_base: 1000
    vrfs:
      - name: default
        vrf_id: 1
        # Checking static route on VRF default is redistributed in a route-map
        static_routes:
          - destination_address_prefix: 66.66.66.0/24
            gateway: 172.17.0.0
            nodes: [cv-pathfinder-edge]
      - name: PROD
        # Showing that wan_vni and vrf_id can be different. `vrf_id` influences the subinterface id.
        vrf_id: 142
        svis:
          - id: 100
            name: VLAN100
            ip_address_virtual: 10.0.100.1/24
      - name: IT
        vrf_id: 1000
    l2vlans:
      - id: 101
        name: VLAN101
  - name: TenantB
    vrfs:
      - name: default
        vrf_id: 1
      - name: TRANSIT
        vrf_id: 66
      # Test that a VRF with address_families: [] on a WAN router is not configured on Vxlan1 interface nor BGP
      - name: NOT-WAN-VRF
        vrf_id: 13
        address_families: []
  - name: TenantC
    mac_vrf_vni_base: 1000
    vrfs:
      # Test adding a VRF on an uplink switch and seeing it configured on the WAN routers
      - name: ATTRACTED-VRF-FROM-UPLINK
        vrf_id: 666
        svis:
          - id: 666
            name: VLAN666
            ip_address_virtual: 10.66.66.66/24
            nodes:
              - node: site-ha-disabled-leaf
                ip_address: 10.66.66.1

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
      wan_vni: 1
    - name: PROD
      policy: PROD-AVT-POLICY
      wan_vni: 42
    # Testing reusing the same policy as default VRF
    - name: IT
      policy: DEFAULT-AVT-POLICY
      wan_vni: 100
    # Testing a VRF only on transit and not edge
    - name: TRANSIT
      policy: TRANSIT-AVT-POLICY
      wan_vni: 66
    - name: ATTRACTED-VRF-FROM-UPLINK
      wan_vni: 166
  policies:
    - name: PROD-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
          - names: [MPLS]
            preference: alternate
      application_virtual_topologies:
        - application_profile: VOICE
          lowest_hop_count: true
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate
          constraints:
            jitter: 42
          id: 2
        - application_profile: VIDEO
          path_groups:
            - names: [MPLS, LTE]
              preference: preferred
            - names: [INET]
              preference: alternate
          constraints:
            loss_rate: 42.0
          id: 4
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          # No prefence to check the default.
          - names: [INET, Equinix]
          - names: [MPLS]
            preference: 42
      application_virtual_topologies:
        - application_profile: VIDEO
          path_groups:
            - names: [MPLS, INET]
              preference: preferred
          id: 3
    - name: TRANSIT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
          - names: [MPLS]
            preference: alternate
      application_virtual_topologies:
        - application_profile: VOICE
          name: CUSTOM-VOICE-PROFILE-NAME
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate
          id: 42

application_classification:
  application_profiles:
    - name: VIDEO
      # Testing categories filtering
      categories:
        - name: VIDEO1
      applications:
        # Testing applications in application-profiles filtering
        - name: CUSTOM-APPLICATION-1
        # Builtin application that should not raise
        - name: skype
    - name: IT
    - name: VOICE
      applications:
        # Testing applications in application-profiles filtering
        - name: CUSTOM-VOICE-APPLICATION
    # This should not be rendered in any device
    - name: NOT-IN-ANY-POLICY
  categories:
    # This should not be rendered in any device
    - name: NOT-IN-ANY-PROFILE
    - name: VIDEO1
      applications:
        # Testing applications in categories filtering
        - name: CUSTOM-APPLICATION-2
        # Builtin application that should not raise
        - name: microsoft-teams
  applications:
    ipv4_applications:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-PROFILE-NOR-CATEGORY
      - name: CUSTOM-APPLICATION-1
        protocols: [tcp]
        # Testing filtering of prefixes
        src_prefix_set_name: CUSTOM-SRC-PREFIX-1
        dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
      - name: CUSTOM-APPLICATION-2
        protocols: [tcp]
        tcp_src_port_set_name: TCP-SRC-2
        tcp_dest_port_set_name: TCP-DEST-2
      - name: CUSTOM-voice-APPLICATION
        protocols: [udp]
        udp_src_port_set_name: UDP-SRC-VOICE
        udp_dest_port_set_name: UDP-DEST-VOICE
  field_sets:
    ipv4_prefixes:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-APPLICATION
      - name: CUSTOM-SRC-PREFIX-1
        prefix_values:
          - 42.42.42.0/24
      - name: CUSTOM-DEST-PREFIX-1
        prefix_values:
          - 6.6.6.0/24
    l4_ports:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-APPLICATION
      - name: TCP-SRC-2
        port_values:
          - 42
      - name: TCP-DEST-2
        port_values:
          - 666
          - 777
      - name: UDP-SRC-VOICE
        port_values:
          - 42000-42999
      - name: UDP-DEST-VOICE
        port_values:
          - 30000-30100
          - 31000-31100
